import 'package:romanice/romanice.dart';

final Map<String, dynamic> standardConverter = <String, dynamic>{
  'fromRoman': FromRoman.standard(),
  'testCases': <Map<String, dynamic>>[
    <String, dynamic>{'decimal': 0, 'roman': ''},
    <String, dynamic>{'decimal': 1, 'roman': 'I'},
    <String, dynamic>{'decimal': 2, 'roman': 'II'},
    <String, dynamic>{'decimal': 3, 'roman': 'III'},
    <String, dynamic>{'decimal': 4, 'roman': 'IV'},
    <String, dynamic>{'decimal': 5, 'roman': 'V'},
    <String, dynamic>{'decimal': 6, 'roman': 'VI'},
    <String, dynamic>{'decimal': 7, 'roman': 'VII'},
    <String, dynamic>{'decimal': 8, 'roman': 'VIII'},
    <String, dynamic>{'decimal': 9, 'roman': 'IX'},
    <String, dynamic>{'decimal': 10, 'roman': 'X'},
    <String, dynamic>{'decimal': 11, 'roman': 'XI'},
    <String, dynamic>{'decimal': 12, 'roman': 'XII'},
    <String, dynamic>{'decimal': 39, 'roman': 'XXXIX'},
    <String, dynamic>{'decimal': 50, 'roman': 'L'},
    <String, dynamic>{'decimal': 100, 'roman': 'C'},
    <String, dynamic>{'decimal': 160, 'roman': 'CLX'},
    <String, dynamic>{'decimal': 207, 'roman': 'CCVII'},
    <String, dynamic>{'decimal': 246, 'roman': 'CCXLVI'},
    <String, dynamic>{'decimal': 500, 'roman': 'D'},
    <String, dynamic>{'decimal': 789, 'roman': 'DCCLXXXIX'},
    <String, dynamic>{'decimal': 1000, 'roman': 'M'},
    <String, dynamic>{'decimal': 1009, 'roman': 'MIX'},
    <String, dynamic>{'decimal': 1066, 'roman': 'MLXVI'},
    <String, dynamic>{'decimal': 1776, 'roman': 'MDCCLXXVI'},
    <String, dynamic>{'decimal': 1912, 'roman': 'MCMXII'},
    <String, dynamic>{'decimal': 1918, 'roman': 'MCMXVIII'},
    <String, dynamic>{'decimal': 1954, 'roman': 'MCMLIV'},
    <String, dynamic>{'decimal': 2014, 'roman': 'MMXIV'},
    <String, dynamic>{'decimal': 2020, 'roman': 'MMXX'},
    <String, dynamic>{'decimal': 2421, 'roman': 'MMCDXXI'},
    <String, dynamic>{'decimal': 3888, 'roman': 'MMMDCCCLXXXVIII'},
    <String, dynamic>{'decimal': 3999, 'roman': 'MMMCMXCIX'},
  ],
};
