name: romanice
version: 1.0.0+1
description: A Dart library for converting to/from Roman numerals, e.g., 3888 ↔ MMMDCCCLXXXVIII
repository: https://github.com/dkin-om/romanice-dart.git
issue_tracker: https://github.com/dkin-om/romanice-dart/issues
homepage: https://github.com/dkin-om/romanice-dart#readme
environment:
  sdk: '>=2.8.1 <3.0.0'
dev_dependencies:
  test: ^1.14.4
