name: romanice
version: 2.0.0-nullsafety.1
description: A Dart library for converting to/from Roman numerals, e.g., 3888 ↔ MMMDCCCLXXXVIII
repository: https://github.com/dkin-om/romanice-dart.git
issue_tracker: https://github.com/dkin-om/romanice-dart/issues
homepage: https://github.com/dkin-om/romanice-dart#readme
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  invertible: ^2.0.0
dev_dependencies:
  test: ^1.14.4
