name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Note that this workflow uses the latest stable version of the Dart SDK.
    # Docker images for other release channels - like dev and beta - are also
    # available. See https://hub.docker.com/r/google/dart/ for the available
    # images.
    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      - name: Activate coverage
        run: dart pub global activate coverage

      - name: Analyze project source
        run: dart analyze --fatal-infos --fatal-warnings

      - name: Run tests
        run: dart test --platform=vm --coverage=coverage

      - name: Format coverage
        run: dart pub global run coverage:format_coverage --packages=.packages --in=coverage/test/ --out=stdout --report-on=lib/ --check-ignore

      - name: Pub publish (dry-run)
        run: dart pub publish --dry-run
